--
-- PostgreSQL database dump
--

\restrict Anug4yiAOrVhr08tqvAFOmfKh7awxHU2rdmsg6OnjH8OQhJmdMcSkmdC6K8yRPP

-- Dumped from database version 15.19 (Debian 15.19-1.pgdg13+2)
-- Dumped by pg_dump version 15.19 (Debian 15.19-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public."TableSessions" DROP CONSTRAINT IF EXISTS "FK_TableSessions_DiningTables_DiningTableId";
ALTER TABLE IF EXISTS ONLY public."Promotions" DROP CONSTRAINT IF EXISTS "FK_Promotions_MenuItems_MenuItemId";
ALTER TABLE IF EXISTS ONLY public."Orders" DROP CONSTRAINT IF EXISTS "FK_Orders_TableSessions_TableSessionId";
ALTER TABLE IF EXISTS ONLY public."OrderItems" DROP CONSTRAINT IF EXISTS "FK_OrderItems_Orders_OrderId";
ALTER TABLE IF EXISTS ONLY public."OrderItemAddons" DROP CONSTRAINT IF EXISTS "FK_OrderItemAddons_OrderItems_OrderItemId";
ALTER TABLE IF EXISTS ONLY public."MenuItems" DROP CONSTRAINT IF EXISTS "FK_MenuItems_Categories_CategoryId";
ALTER TABLE IF EXISTS ONLY public."Addons" DROP CONSTRAINT IF EXISTS "FK_Addons_MenuItems_MenuItemId";
DROP INDEX IF EXISTS public."IX_Users_Email";
DROP INDEX IF EXISTS public."IX_TableSessions_DiningTableId";
DROP INDEX IF EXISTS public."IX_TableSessions_AccessToken";
DROP INDEX IF EXISTS public."IX_Promotions_MenuItemId";
DROP INDEX IF EXISTS public."IX_Promotions_EndsAt";
DROP INDEX IF EXISTS public."IX_Orders_TableSessionId";
DROP INDEX IF EXISTS public."IX_Orders_PublicId";
DROP INDEX IF EXISTS public."IX_OrderItems_OrderId";
DROP INDEX IF EXISTS public."IX_OrderItemAddons_OrderItemId";
DROP INDEX IF EXISTS public."IX_MenuItems_CategoryId";
DROP INDEX IF EXISTS public."IX_DayPasscodes_Day";
DROP INDEX IF EXISTS public."IX_AuditLogs_CreatedAt";
DROP INDEX IF EXISTS public."IX_Addons_MenuItemId";
ALTER TABLE IF EXISTS ONLY public."__EFMigrationsHistory" DROP CONSTRAINT IF EXISTS "PK___EFMigrationsHistory";
ALTER TABLE IF EXISTS ONLY public."Users" DROP CONSTRAINT IF EXISTS "PK_Users";
ALTER TABLE IF EXISTS ONLY public."TableSessions" DROP CONSTRAINT IF EXISTS "PK_TableSessions";
ALTER TABLE IF EXISTS ONLY public."Promotions" DROP CONSTRAINT IF EXISTS "PK_Promotions";
ALTER TABLE IF EXISTS ONLY public."Orders" DROP CONSTRAINT IF EXISTS "PK_Orders";
ALTER TABLE IF EXISTS ONLY public."OrderItems" DROP CONSTRAINT IF EXISTS "PK_OrderItems";
ALTER TABLE IF EXISTS ONLY public."OrderItemAddons" DROP CONSTRAINT IF EXISTS "PK_OrderItemAddons";
ALTER TABLE IF EXISTS ONLY public."MenuItems" DROP CONSTRAINT IF EXISTS "PK_MenuItems";
ALTER TABLE IF EXISTS ONLY public."DiningTables" DROP CONSTRAINT IF EXISTS "PK_DiningTables";
ALTER TABLE IF EXISTS ONLY public."DayPasscodes" DROP CONSTRAINT IF EXISTS "PK_DayPasscodes";
ALTER TABLE IF EXISTS ONLY public."Categories" DROP CONSTRAINT IF EXISTS "PK_Categories";
ALTER TABLE IF EXISTS ONLY public."AuditLogs" DROP CONSTRAINT IF EXISTS "PK_AuditLogs";
ALTER TABLE IF EXISTS ONLY public."Addons" DROP CONSTRAINT IF EXISTS "PK_Addons";
DROP TABLE IF EXISTS public."__EFMigrationsHistory";
DROP TABLE IF EXISTS public."Users";
DROP TABLE IF EXISTS public."TableSessions";
DROP TABLE IF EXISTS public."Promotions";
DROP TABLE IF EXISTS public."Orders";
DROP TABLE IF EXISTS public."OrderItems";
DROP TABLE IF EXISTS public."OrderItemAddons";
DROP TABLE IF EXISTS public."MenuItems";
DROP TABLE IF EXISTS public."DiningTables";
DROP TABLE IF EXISTS public."DayPasscodes";
DROP TABLE IF EXISTS public."Categories";
DROP TABLE IF EXISTS public."AuditLogs";
DROP TABLE IF EXISTS public."Addons";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Addons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Addons" (
    "Id" integer NOT NULL,
    "MenuItemId" integer NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "Available" boolean NOT NULL
);


--
-- Name: Addons_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Addons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Addons_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AuditLogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AuditLogs" (
    "Id" integer NOT NULL,
    "EntityType" character varying(80) NOT NULL,
    "EntityId" character varying(80) NOT NULL,
    "Action" character varying(80) NOT NULL,
    "FromValue" text,
    "ToValue" text,
    "ActorUserId" text,
    "ActorName" character varying(200),
    "IpAddress" character varying(64),
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "SortOrder" integer DEFAULT 0 NOT NULL
);


--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DayPasscodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DayPasscodes" (
    "Id" integer NOT NULL,
    "Day" date NOT NULL,
    "Code" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RotatedAt" timestamp with time zone
);


--
-- Name: DayPasscodes_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."DayPasscodes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DayPasscodes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DiningTables; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DiningTables" (
    "Id" integer NOT NULL,
    "Label" character varying(40) NOT NULL,
    "Active" boolean NOT NULL
);


--
-- Name: DiningTables_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."DiningTables" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DiningTables_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MenuItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MenuItems" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Price" numeric(10,2) NOT NULL,
    "CategoryId" integer,
    "Available" boolean NOT NULL,
    "PhotoData" bytea,
    "PhotoContentType" character varying(80)
);


--
-- Name: MenuItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."MenuItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MenuItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrderItemAddons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."OrderItemAddons" (
    "Id" integer NOT NULL,
    "OrderItemId" integer NOT NULL,
    "AddonId" integer NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Price" numeric(10,2) NOT NULL
);


--
-- Name: OrderItemAddons_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."OrderItemAddons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItemAddons_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrderItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."OrderItems" (
    "Id" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "MenuItemId" integer NOT NULL,
    "MenuItemName" character varying(200) NOT NULL,
    "UnitPrice" numeric(10,2) NOT NULL,
    "Quantity" integer NOT NULL,
    "Notes" text,
    "LineTotal" numeric(10,2) NOT NULL
);


--
-- Name: OrderItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."OrderItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Orders" (
    "Id" integer NOT NULL,
    "TableSessionId" integer,
    "TableLabel" character varying(40),
    "Status" character varying(40) NOT NULL,
    "CustomerNotes" text,
    "Total" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "PublicId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);


--
-- Name: Orders_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Promotions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Promotions" (
    "Id" integer NOT NULL,
    "MenuItemId" integer NOT NULL,
    "PromoPrice" numeric(10,2) NOT NULL,
    "StartsAt" timestamp with time zone NOT NULL,
    "EndsAt" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL
);


--
-- Name: Promotions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Promotions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Promotions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TableSessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."TableSessions" (
    "Id" integer NOT NULL,
    "DiningTableId" integer NOT NULL,
    "AccessToken" character varying(80) NOT NULL,
    "OpenedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "ClosedAt" timestamp with time zone,
    "SpendingCap" numeric(10,2),
    "GuestName" character varying(80)
);


--
-- Name: TableSessions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."TableSessions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TableSessions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(40) NOT NULL,
    "Active" boolean NOT NULL
);


--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: Addons; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AuditLogs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: DayPasscodes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: DiningTables; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: MenuItems; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: OrderItemAddons; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: OrderItems; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: Promotions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: TableSessions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Users" VALUES (1, 'Admin GoServ', 'admin@goserv.local', '$2a$11$yvVUq8OrZ9kGGZbTn/vpteAAtdCg99Cye2O20bHpowMALG9HF5hbe', 'Admin', true);
INSERT INTO public."Users" VALUES (2, 'Cozinha', 'cozinha@goserv.local', '$2a$11$8PEyZCEBiIKAqoxJY8Xo5O6DiDVhb5BDzDGV1CfpgfNexo0NOMVUm', 'Kitchen', true);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260827_InitialCreate', '8.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260829_AddAuthAndTables', '8.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260829_AddOrdersAndAddons', '8.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260829_AddPhotoUrlAndSortOrder', '8.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260829_AddPromotions', '8.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260829_AddSecurityAuditAndPublicId', '8.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260829_DayPasscodeAndGuestName', '8.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260829_StorePhotosInDatabase', '8.0.8');


--
-- Name: Addons_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Addons_Id_seq"', 1, false);


--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AuditLogs_Id_seq"', 1, false);


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 1, false);


--
-- Name: DayPasscodes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."DayPasscodes_Id_seq"', 1, false);


--
-- Name: DiningTables_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."DiningTables_Id_seq"', 1, false);


--
-- Name: MenuItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."MenuItems_Id_seq"', 1, false);


--
-- Name: OrderItemAddons_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."OrderItemAddons_Id_seq"', 1, false);


--
-- Name: OrderItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."OrderItems_Id_seq"', 1, false);


--
-- Name: Orders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Orders_Id_seq"', 1, false);


--
-- Name: Promotions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Promotions_Id_seq"', 1, false);


--
-- Name: TableSessions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."TableSessions_Id_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 2, true);


--
-- Name: Addons PK_Addons; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Addons"
    ADD CONSTRAINT "PK_Addons" PRIMARY KEY ("Id");


--
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: DayPasscodes PK_DayPasscodes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DayPasscodes"
    ADD CONSTRAINT "PK_DayPasscodes" PRIMARY KEY ("Id");


--
-- Name: DiningTables PK_DiningTables; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DiningTables"
    ADD CONSTRAINT "PK_DiningTables" PRIMARY KEY ("Id");


--
-- Name: MenuItems PK_MenuItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MenuItems"
    ADD CONSTRAINT "PK_MenuItems" PRIMARY KEY ("Id");


--
-- Name: OrderItemAddons PK_OrderItemAddons; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItemAddons"
    ADD CONSTRAINT "PK_OrderItemAddons" PRIMARY KEY ("Id");


--
-- Name: OrderItems PK_OrderItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id");


--
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- Name: Promotions PK_Promotions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Promotions"
    ADD CONSTRAINT "PK_Promotions" PRIMARY KEY ("Id");


--
-- Name: TableSessions PK_TableSessions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TableSessions"
    ADD CONSTRAINT "PK_TableSessions" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Addons_MenuItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Addons_MenuItemId" ON public."Addons" USING btree ("MenuItemId");


--
-- Name: IX_AuditLogs_CreatedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AuditLogs_CreatedAt" ON public."AuditLogs" USING btree ("CreatedAt");


--
-- Name: IX_DayPasscodes_Day; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_DayPasscodes_Day" ON public."DayPasscodes" USING btree ("Day");


--
-- Name: IX_MenuItems_CategoryId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MenuItems_CategoryId" ON public."MenuItems" USING btree ("CategoryId");


--
-- Name: IX_OrderItemAddons_OrderItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_OrderItemAddons_OrderItemId" ON public."OrderItemAddons" USING btree ("OrderItemId");


--
-- Name: IX_OrderItems_OrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_OrderItems_OrderId" ON public."OrderItems" USING btree ("OrderId");


--
-- Name: IX_Orders_PublicId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Orders_PublicId" ON public."Orders" USING btree ("PublicId");


--
-- Name: IX_Orders_TableSessionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_TableSessionId" ON public."Orders" USING btree ("TableSessionId");


--
-- Name: IX_Promotions_EndsAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Promotions_EndsAt" ON public."Promotions" USING btree ("EndsAt");


--
-- Name: IX_Promotions_MenuItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Promotions_MenuItemId" ON public."Promotions" USING btree ("MenuItemId");


--
-- Name: IX_TableSessions_AccessToken; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_TableSessions_AccessToken" ON public."TableSessions" USING btree ("AccessToken");


--
-- Name: IX_TableSessions_DiningTableId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_TableSessions_DiningTableId" ON public."TableSessions" USING btree ("DiningTableId");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- Name: Addons FK_Addons_MenuItems_MenuItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Addons"
    ADD CONSTRAINT "FK_Addons_MenuItems_MenuItemId" FOREIGN KEY ("MenuItemId") REFERENCES public."MenuItems"("Id") ON DELETE CASCADE;


--
-- Name: MenuItems FK_MenuItems_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MenuItems"
    ADD CONSTRAINT "FK_MenuItems_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE SET NULL;


--
-- Name: OrderItemAddons FK_OrderItemAddons_OrderItems_OrderItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItemAddons"
    ADD CONSTRAINT "FK_OrderItemAddons_OrderItems_OrderItemId" FOREIGN KEY ("OrderItemId") REFERENCES public."OrderItems"("Id") ON DELETE CASCADE;


--
-- Name: OrderItems FK_OrderItems_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- Name: Orders FK_Orders_TableSessions_TableSessionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_TableSessions_TableSessionId" FOREIGN KEY ("TableSessionId") REFERENCES public."TableSessions"("Id") ON DELETE SET NULL;


--
-- Name: Promotions FK_Promotions_MenuItems_MenuItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Promotions"
    ADD CONSTRAINT "FK_Promotions_MenuItems_MenuItemId" FOREIGN KEY ("MenuItemId") REFERENCES public."MenuItems"("Id") ON DELETE CASCADE;


--
-- Name: TableSessions FK_TableSessions_DiningTables_DiningTableId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TableSessions"
    ADD CONSTRAINT "FK_TableSessions_DiningTables_DiningTableId" FOREIGN KEY ("DiningTableId") REFERENCES public."DiningTables"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict Anug4yiAOrVhr08tqvAFOmfKh7awxHU2rdmsg6OnjH8OQhJmdMcSkmdC6K8yRPP

